### ISSUE TITLE
Strange behaviour while running tests

### ISSUE THREAD

**Issue by 0xNaN** [eproxus/meck#158]
Hi,
I'm new to Erlang, rebar3 and meck so I'm sorry if I'm missing something with this issue.
I've two suite of tests: `peer.hrl` and `mymock.hrl`.
In the former I'm using meck to create a mock of `mymock` module, while in the latter I've only tests of the real implementation of `mymock`.

If I run the tests with `rebar3 eunit --module mymock`  and `rebar3 eunit --module peer` everything is working, but when I run all the tests with `rebar eunit` I get the following error:

```
===> Verifying dependencies...
===> Compiling app
===> Performing EUnit tests...
..
Pending:
  undefined
    %% Related process exited with reason: killed


Finished in ? seconds
6 tests, 0 failures, 4 cancelled
===> Error running tests
```

I've noticed that the issue is related to the order in which the tests are running, indeed the error keeps if I run `rebar3 eunit --module=mymock,peer` but disappears if I use `rebar3 eunit --module=peer,mymock`.

An example of the issue can be found [here](https://github.com/0xNaN/meck_issue).
Any help? really thank you!

**Comment by eproxus** [comment]
Adding some debug output shows that both tests are running (as also the two dots `.` show):

```
$ rebar3 eunit --module=mymock,peer
===> Verifying dependencies...
===> Compiling app
===> Performing EUnit tests...
mymock setup
mymock teardown
mymock teardown
.peer setup
peer test
peer teardown
.
Pending:
  undefined
    %% Related process exited with reason: killed


Finished in ? seconds
4 tests, 0 failures, 2 cancelled
===> Error running tests
```

Since mymock is reloaded twice (once when the mock is created and once when the mock is unloaded) I suspect there is some test process owned by Rebar that gets killed (an Erlang process that is "stuck" in a module that gets reloaded twice gets killed). I'm not entirely sure why this happens, it's either a factor of how Rebar3 runs tests or how EUnit works.

If you move the tests from header files to real test modules (e.g. `peer_tests.erl`) you can avoid this problem.

**Comment by pselden** [comment]
Sorry for the late necro, but I'm encountering this issue when I'm using actual test files. Did anyone else find a solution to this?
