### ISSUE TITLE
Porting ExUnit.CaptureIO to Erlang?

### ISSUE THREAD

**Issue by marco-m** [eproxus/meck#171]
Hello Adam,

I just discovered Elixir [ExUnit.CaptureIO](https://hexdocs.pm/ex_unit/ExUnit.CaptureIO.html) (Functionality to capture IO for testing, part of the Elixir standard library) and I think that Erlang badly needs the equivalent.

I want to give it a try. I wanted to know if you would consider incorporating this functionality in Meck or if you think it would not fit.

**Comment by eproxus** [comment]
I think it's a cool feature, but AFAIK [EUnit already does this](http://erlang.org/doc/apps/eunit/chapter.html#EUnit_captures_standard_output). The way it's implemented is just changing the [group leader](http://erlang.org/doc/man/erlang.html#group_leader-0) which I think is also what EUnit does.

If you want to implement this yourself, it should be easy to do it in a function like ExUnit. However, I don't think this should go into Meck because it is not strictly mocking related. I'm not totally against it if it turns out the code is short and sweet enough, but it could as well be in an external library.

**Comment by marco-m** [comment]
Thanks for answering :-) Unfortunately the link about EUnit is the opposite direction: EUnit swallows output, yes. The power of CaptureIO is, from the test, to tell to the mock IO the data to feed to the UUT when it will run, it is the opposite direction. This would allow to test a function that reads from stdin, to make an example. It can also do the opposite, read what the UUT writes to output. This in my understanding would be more akin to what you mention about EUnit.

In any case, time for me to try it out and then come back. Thanks Adam.

**Comment by eproxus** [comment]
Ah, true, CaptureIO allows you to operate on the output. Then it makes sense to add to Erlang as well.

**Comment by marco-m** [comment]
Yes, now maybe you can see the full power of CaptureIO in its simplicity and usefulness :-)

**Comment by marco-m** [comment]
This is what I came up with: mock_io https://github.com/marco-m/mock_io
I am very interested in your feedback if you have time :-)
I am closing this ticket because I agree this is not really meck related.
