### ISSUE TITLE
How to install meck on windows

### ISSUE THREAD

**Issue by chenmurong** [eproxus/meck#237]
How to install meck on windows

## Reproduction Steps

I have a project with erlang on Windows 10, now,
I want to build EUnit, but EUnit not mock function, So，I want EUnit mock By Meck .
Buy meck install not  on windows document. Can you tell me how to install meck on windows. Sincere thanks

## Versions

Erlang/OTP 24
OS: windows 10

**Comment by eproxus** [comment]
Hi @chenmurong!

I'd recommend creating a project using Rebar 3 and adding Meck as a dependency. You can check their getting started guide for Windows [here](http://rebar3.org/docs/getting-started/#windows). 

For these kinds of support questions, please [open a discussion topic](https://github.com/eproxus/meck/discussions/new) instead of an issue. 🙂

**Comment by chenmurong** [comment]
> Hi @chenmurong!
> 
> I'd recommend creating a project using Rebar 3 and adding Meck as a dependency. You can check their getting started guide for Windows [here](http://rebar3.org/docs/getting-started/#windows).
> 
> For these kinds of support questions, please [open a discussion topic](https://github.com/eproxus/meck/discussions/new) instead of an issue. 🙂

Understand，Thanks。This is my first question, I will remember it later🙂
